job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/acoustic121/jenkins.git", 'main')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'Jenkins_Upgradev3-master\\maven-samples\\single-module')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}